

###
GET http://localhost:4000/api/rooms

###
POST http://localhost:4000/api/rooms
Content-Type: application/json

{
     "name": "testing room 2",
    "price": 400,
    "desc": "some description 2",
    "roomNumbers": [{
        "number": 202,
        "unavailableDates": ["2026-04-21", "2026-04-23"]
    }]
}

# get singe room
###
GET http://localhost:4000/api/rooms/69e7946aec1e8ccca649fe20

# update room
###
PUT http://localhost:4000/api/rooms/69e7946aec1e8ccca649fe20
Content-Type: application/json

{
     "name": "testing room updated",
    "price": 300,
    "desc": "test description update"
}

# delete room
###
DELETE http://localhost:4000/api/rooms/69e7946aec1e8ccca649fe20

# get bookings
###
GET http://localhost:4000/api/bookings

# get single booking
###
GET  http://localhost:4000/api/bookings/69e8c34bcd5ad0ef4f7ae2fd

#create booking
###
POST http://localhost:4000/api/bookings
Content-Type: application/json

{
    "roomId": "69e79573ec1e8ccca649fe22",
    "name": "uche",
    "email": "uche@gmail.com",
    "checkInDate": "2026-04-23",
    "checkOutDate": "2026-04-24"
}

# update booking
###
PUT  http://localhost:4000/api/bookings/69e8c34bcd5ad0ef4f7ae2fd
Content-Type: application/json

{
    "name": "Somto updated",
    "email": "somto@gmail.com"
}

# delete booking
###
DELETE  http://localhost:4000/api/bookings/69e8c34bcd5ad0ef4f7ae2fd